// Fase 2: reemplazar con llamadas a /api/admin/documentos
export const ADMIN_MOCK_DOCS = [
  { id: 1, nombre: 'Mapa Base Chocó 2024',           categoria: 'Cartografía',          tipo: 'PDF',     autor: 'Equipo Cartográfico',  fecha: '15 Mar 2026', tamano: '4.2 MB',  descargas: 142, url: null },
  { id: 2, nombre: 'Estudio Cobertura Vegetal 2024',  categoria: 'Estudios Ambientales', tipo: 'PDF',     autor: 'Laboratorio SIG',      fecha: '10 Mar 2026', tamano: '8.7 MB',  descargas: 98,  url: null },
  { id: 3, nombre: 'Red Hidrográfica Pacífico',       categoria: 'Hidrología',           tipo: 'IMG',     autor: 'Equipo Hidrografía',   fecha: '05 Mar 2026', tamano: '12.1 MB', descargas: 67,  url: null },
  { id: 4, nombre: 'Zonificación Ambiental 2023',     categoria: 'Cartografía',          tipo: 'PDF',     autor: 'Gestión Territorial',  fecha: '28 Feb 2026', tamano: '6.3 MB',  descargas: 215, url: null },
  { id: 5, nombre: 'Informe Biodiversidad Q4-2025',   categoria: 'Biodiversidad',        tipo: 'PDF',     autor: 'Equipo Biodiversidad', fecha: '20 Feb 2026', tamano: '3.8 MB',  descargas: 54,  url: null },
  { id: 6, nombre: 'Normativa Ambiental Chocó 2024',  categoria: 'Normativa',            tipo: 'PDF',     autor: 'Jurídica IIAP',        fecha: '15 Feb 2026', tamano: '2.1 MB',  descargas: 183, url: null },
  { id: 7, nombre: 'Geovisor — Cuencas Hidrográficas',categoria: 'Hidrología',           tipo: 'Geovisor',autor: 'Geoportal Regional',   fecha: '10 Feb 2026', tamano: '—',       descargas: 312, url: '/geovisor' },
  { id: 8, nombre: 'Imagen Satelital Atrato 2025',    categoria: 'Cartografía',          tipo: 'IMG',     autor: 'Teledetección IIAP',   fecha: '05 Feb 2026', tamano: '22.4 MB', descargas: 78,  url: null },
]

export const DOC_CATEGORIES = [
  {
    id: 'protocolos',
    title: 'Protocolos Ambientales',
    subtitle: '12 documentos actualizados',
    icon: 'Waves',
    color: 'border-l-primary-800',
    docs: [
      {
        name: 'Protocolo_Monitoreo_Biodiversidad_V2.pdf',
        type: 'pdf',
        size: '4.2 MB',
        updated: '12 Oct 2023',
        dateISO: '2023-10-12',
        url: null,
      },
      {
        name: 'Guía_Ética_Trabajo_Comunitario.docx',
        type: 'docx',
        size: '1.8 MB',
        updated: '05 Sep 2023',
        dateISO: '2023-09-05',
        url: null,
      },
      {
        name: 'Protocolo_Muestreo_Suelos_V3.pdf',
        type: 'pdf',
        size: '3.1 MB',
        updated: '22 Ago 2023',
        dateISO: '2023-08-22',
        url: null,
      },
      {
        name: 'Manual_Seguridad_Campo.pdf',
        type: 'pdf',
        size: '2.5 MB',
        updated: '14 Jul 2023',
        dateISO: '2023-07-14',
        url: null,
      },
    ],
  },
  {
    id: 'formatos',
    title: 'Formatos y Plantillas',
    subtitle: '8 recursos disponibles',
    icon: 'FileInput',
    color: 'border-l-gold-400',
    docs: [
      {
        name: 'Formato_Captura_Datos_Campo_V4.xlsx',
        type: 'xlsx',
        size: '156 KB',
        updated: '10 Nov 2023',
        dateISO: '2023-11-10',
        url: null,
      },
      {
        name: 'Plantilla_Informe_Técnico.docx',
        type: 'docx',
        size: '98 KB',
        updated: '08 Oct 2023',
        dateISO: '2023-10-08',
        url: null,
      },
    ],
  },
  {
    id: 'guias',
    title: 'Guías Técnicas Geográficas',
    subtitle: '15 manuales detallados',
    icon: 'BookOpen',
    color: 'border-l-primary-500',
    docs: [
      {
        name: 'Guía_Uso_Geovisor_SIAT_PC.pdf',
        type: 'pdf',
        size: '4.2 MB',
        updated: '15 Nov 2023',
        dateISO: '2023-11-15',
        url: null,
      },
      {
        name: 'Manual_PostGIS_Básico.pdf',
        type: 'pdf',
        size: '6.8 MB',
        updated: '20 Sep 2023',
        dateISO: '2023-09-20',
        url: null,
      },
      {
        name: 'Guía_Procesamiento_Imágenes_Satelitales.pdf',
        type: 'pdf',
        size: '5.1 MB',
        updated: '03 Ago 2023',
        dateISO: '2023-08-03',
        url: null,
      },
    ],
  },
  {
    id: 'estadisticos',
    title: 'Datos Estadísticos y Reportes',
    subtitle: '4 informes anuales',
    icon: 'TrendingUp',
    color: 'border-l-primary-300',
    docs: [
      {
        name: 'Estadísticas_Biodiversidad_2023.xlsx',
        type: 'xlsx',
        size: '2.8 MB',
        updated: '20 Dic 2023',
        dateISO: '2023-12-20',
        url: null,
      },
      {
        name: 'Reporte_Anual_Deforestación_Chocó.pdf',
        type: 'pdf',
        size: '7.4 MB',
        updated: '15 Dic 2023',
        dateISO: '2023-12-15',
        url: null,
      },
    ],
  },
]
