// Fase 2: reemplazar con llamadas a /api/admin/mapas
export const ADMIN_MOCK_MAPAS = [
  { id: 1, nombre: 'Red Hidrográfica del Pacífico',     tematica: 'Hidrología',       escala: '1:100.000', autor: 'Equipo Hidrografía',  fecha: '15 Mar 2026', visible: true,  consultas: 418, formato: 'PDF',     url: null    },
  { id: 2, nombre: 'Mapa Base Chocó Biogeográfico',     tematica: 'Cartografía Base', escala: '1:250.000', autor: 'Equipo Cartográfico', fecha: '10 Mar 2026', visible: true,  consultas: 634, formato: 'IMG',     url: null    },
  { id: 3, nombre: 'Distribución de Especies Endémicas',tematica: 'Biodiversidad',    escala: '1:50.000',  autor: 'Lab. Biodiversidad',  fecha: '05 Mar 2026', visible: true,  consultas: 287, formato: 'PDF',     url: null    },
  { id: 4, nombre: 'Zonificación Ambiental 2024',       tematica: 'Zonificación',     escala: '1:100.000', autor: 'Gestión Territorial', fecha: '28 Feb 2026', visible: true,  consultas: 512, formato: 'PDF',     url: null    },
  { id: 5, nombre: 'Infraestructura Vial — Quibdó',     tematica: 'Infraestructura',  escala: '1:25.000',  autor: 'SIG Institucional',   fecha: '20 Feb 2026', visible: false, consultas: 156, formato: 'IMG',     url: null    },
  { id: 6, nombre: 'Zonas de Riesgo por Inundación',    tematica: 'Riesgo',           escala: '1:50.000',  autor: 'Gestión del Riesgo',  fecha: '15 Feb 2026', visible: true,  consultas: 329, formato: 'PDF',     url: null    },
  { id: 7, nombre: 'Cobertura Vegetal 2024',            tematica: 'Biodiversidad',    escala: '1:100.000', autor: 'Teledetección IIAP',  fecha: '10 Feb 2026', visible: true,  consultas: 445, formato: 'PDF',     url: null    },
  { id: 8, nombre: 'Áreas Protegidas del Chocó',        tematica: 'Zonificación',     escala: '1:250.000', autor: 'SIG Institucional',   fecha: '05 Feb 2026', visible: true,  consultas: 597, formato: 'Geovisor',url: '/geovisor' },
]

export const MAP_CATEGORIES = [
  { value: '', label: 'Todas las categorías' },
  { value: 'biodiversidad', label: 'Biodiversidad y Especies' },
  { value: 'hidrologia', label: 'Hidrología' },
  { value: 'planificacion', label: 'Planificación' },
  { value: 'ecosistemas', label: 'Ecosistemas' },
  { value: 'cobertura', label: 'Cobertura Vegetal' },
  { value: 'comunidades', label: 'Comunidades' },
]

export const MAP_DEPARTMENTS = [
  { value: '', label: 'Todo el Chocó' },
  { value: 'choco', label: 'Chocó' },
  { value: 'valle', label: 'Valle del Cauca' },
  { value: 'cauca', label: 'Cauca' },
  { value: 'narino', label: 'Nariño' },
  { value: 'costa-norte', label: 'Costa Norte (Chocó)' },
]

export const MAP_FORMATS = [
  { value: '', label: 'Todos los formatos' },
  { value: 'pdf', label: 'PDF' },
  { value: 'img', label: 'Imagen' },
]

export const MAP_YEARS = [
  { value: '', label: 'Todos los años' },
  { value: '2024', label: '2024 - Reciente' },
  { value: '2023', label: '2023' },
  { value: '2022', label: '2022' },
  { value: '2021', label: '2021' },
]

export const SAMPLE_MAPS = [
  {
    id: 'MAPA_REF_01',
    categoryKey: 'cobertura',
    category: 'Cobertura Vegetal',
    department: 'choco',
    year: '2023',
    title: 'Mapa de Cobertura Vegetal y Uso de la Tierra',
    excerpt: 'Análisis detallado de los estratos vegetales del Chocó con clasificación por tipo de cobertura.',
    formats: ['PDF', 'IMG'],
    badge: 'PDF',
    badgeColor: 'primary',
    date: 'Sep 2023',
    geovisorLink: '/geovisor',
  },
  {
    id: 'MAPA_REF_02',
    categoryKey: 'hidrologia',
    category: 'Hidrología',
    department: 'choco',
    year: '2024',
    title: 'Cuenca del Río Atrato: Dinámica Fluvial',
    excerpt: 'Cartografía multitemporal de la red hídrica principal y sus afluentes en la cuenca del Atrato.',
    formats: ['PDF', 'IMG'],
    badge: 'PDF + IMG',
    badgeColor: 'primary',
    date: 'Jun 2024',
    geovisorLink: '/geovisor',
  },
  {
    id: 'MAPA_REF_03',
    categoryKey: 'planificacion',
    category: 'Planificación',
    department: 'narino',
    year: '2023',
    title: 'Mapa de Conflictos de Uso del Suelo 2023',
    excerpt: 'Identificación de áreas con sobreuso y subuso del suelo en municipios del Pacífico colombiano.',
    formats: ['PDF', 'IMG'],
    badge: 'PDF',
    badgeColor: 'primary',
    date: 'Ene 2024',
    geovisorLink: '/geovisor',
  },
  {
    id: 'MAPA_REF_04',
    categoryKey: 'ecosistemas',
    category: 'Ecosistemas',
    department: 'valle',
    year: '2024',
    title: 'Zonificación Ambiental del Pacífico Norte',
    excerpt: 'Delimitación de áreas de conservación y uso sostenible con criterios ambientales integrados.',
    formats: ['PDF', 'IMG'],
    badge: 'IMG',
    badgeColor: 'orange',
    date: 'Mar 2024',
    geovisorLink: '/geovisor',
  },
  {
    id: 'MAPA_REF_05',
    categoryKey: 'hidrologia',
    category: 'Hidrología',
    department: 'choco',
    year: '2024',
    title: 'Red Hídrica y Cuencas Hidrográficas Sector Atrato',
    excerpt: 'Mapeo completo de ríos tributarios y microcuencas del sector medio y bajo del río Atrato.',
    formats: ['PDF'],
    badge: 'PDF',
    badgeColor: 'primary',
    date: 'Abr 2024',
    geovisorLink: '/geovisor',
  },
  {
    id: 'MAPA_REF_06',
    categoryKey: 'planificacion',
    category: 'Planificación',
    department: 'cauca',
    year: '2024',
    title: 'Áreas de Reserva Forestal del Pacífico',
    excerpt: 'Cartografía oficial de las zonas de reserva forestal con delimitación legal actualizada.',
    formats: ['PDF', 'IMG'],
    badge: 'PDF + IMG',
    badgeColor: 'primary',
    date: 'Feb 2024',
    geovisorLink: '/geovisor',
  },
]
