export const NEWS = [
  {
    id: 1,
    slug: 'nueva-capa-reservas-naturales-2024',
    tag: 'ACTUALIZACIÓN DE DATOS',
    title: 'Publicada nueva capa cartográfica de Reservas Naturales de la Sociedad Civil 2024.',
    excerpt: 'La actualización incluye 14 nuevas reservas en el departamento del Chocó, sumando más de...',
    time: 'Hace 2 horas',
    author: 'Geoportal Regional',
  },
  {
    id: 2,
    slug: 'encuentro-planificadores-territoriales',
    tag: 'EVENTO REGIONAL',
    title: 'Encuentro de Planificadores Territoriales: Desafíos del cambio climático en el litoral Pacífico.',
    excerpt: 'Representantes de 4 departamentos se reunirán en Quibdó para unificar criterios de resiliencia...',
    time: 'Hace 1 día',
    author: 'Evento',
  },
]

export const ALL_NEWS = [
  {
    id: 1,
    slug: 'nueva-capa-reservas-naturales-2024',
    tag: 'ACTUALIZACIÓN DE DATOS',
    tagColor: 'primary',
    title: 'Publicada nueva capa cartográfica de Reservas Naturales de la Sociedad Civil 2024.',
    excerpt: 'La actualización incluye 14 nuevas reservas en el departamento del Chocó, sumando más de...',
    content: 'La actualización incluye 14 nuevas reservas en el departamento del Chocó, sumando más de 45,000 hectáreas al inventario de áreas protegidas de la sociedad civil. Esta nueva capa cartográfica permite identificar con precisión los límites de cada reserva, facilitando los procesos de planificación territorial y monitoreo ambiental.\n\nEl equipo técnico del IIAP realizó el levantamiento de información en campo durante los meses de agosto y septiembre de 2024, utilizando equipos GPS de alta precisión y verificando los límites con las comunidades locales.\n\nLa capa está disponible para descarga en formato PDF e imagen desde el Repositorio de Mapas, y puede visualizarse interactivamente en el Geovisor SIAT-PC.',
    time: 'Hace 2 horas',
    date: '01 Abril 2026',
    author: 'Geoportal Regional',
    category: 'Ambiente',
  },
  {
    id: 2,
    slug: 'encuentro-planificadores-territoriales',
    tag: 'EVENTO REGIONAL',
    tagColor: 'gold',
    title: 'Encuentro de Planificadores Territoriales: Desafíos del cambio climático en el litoral Pacífico.',
    excerpt: 'Representantes de 4 departamentos se reunirán en Quibdó para unificar criterios de resiliencia...',
    content: 'Representantes de los departamentos de Chocó, Valle del Cauca, Cauca y Nariño se reunirán en la ciudad de Quibdó los días 15 y 16 de abril de 2026 para unificar criterios de resiliencia climática en la planificación territorial del litoral Pacífico colombiano.\n\nEl encuentro, organizado por el IIAP en coordinación con el Ministerio de Ambiente y Desarrollo Sostenible, abordará temas como la gestión del riesgo por inundaciones, la erosión costera y la protección de manglares como barreras naturales.\n\nSe espera la participación de más de 120 planificadores territoriales, funcionarios ambientales y líderes comunitarios de la región.',
    time: 'Hace 1 día',
    date: '31 Marzo 2026',
    author: 'Coordinación de Eventos IIAP',
    category: 'Social',
  },
  {
    id: 3,
    slug: 'lanzamiento-geoportal-biodiversidad',
    tag: 'TECNOLOGÍA',
    tagColor: 'primary',
    title: 'Lanzamiento del nuevo Geoportal de Biodiversidad del Chocó Biogeográfico.',
    excerpt: 'Nuevas capas de información geográfica ahora disponibles para consulta pública con datos actualizados...',
    content: 'El Instituto de Investigaciones Ambientales del Pacífico lanza oficialmente el Geoportal de Biodiversidad, una herramienta que integra más de 200 capas de información geográfica sobre la diversidad biológica del Chocó Biogeográfico.\n\nEl geoportal incluye datos de distribución de especies endémicas, áreas de importancia para la conservación, corredores biológicos y zonas de amortiguamiento. Toda la información está disponible para consulta pública y descarga.\n\nEste desarrollo representa un avance significativo en la democratización de la información ambiental de la región.',
    time: 'Hace 3 días',
    date: '29 Marzo 2026',
    author: 'Laboratorio de Datos IIAP',
    category: 'Ambiente',
  },
  {
    id: 4,
    slug: 'taller-herramientas-sig-comunidades',
    tag: 'CAPACITACIÓN',
    tagColor: 'gold',
    title: 'Taller de Herramientas SIG para comunidades del medio Atrato.',
    excerpt: 'Capacitación técnica en el uso de mapas digitales para líderes comunitarios del Chocó...',
    content: 'El IIAP realizó con éxito el taller de capacitación en Herramientas SIG dirigido a 35 líderes comunitarios del medio Atrato. Los participantes aprendieron a utilizar el Geovisor SIAT-PC para consultar información territorial de sus comunidades.\n\nEl taller incluyó módulos prácticos sobre lectura de mapas digitales, uso de coordenadas GPS y generación de reportes territoriales básicos.\n\nEsta iniciativa forma parte del programa de transferencia tecnológica del instituto, que busca empoderar a las comunidades locales en la gestión de su territorio.',
    time: 'Hace 5 días',
    date: '27 Marzo 2026',
    author: 'Programa de Extensión IIAP',
    category: 'Social',
  },
  {
    id: 5,
    slug: 'actualizacion-datos-hidrograficos',
    tag: 'ACTUALIZACIÓN DE DATOS',
    tagColor: 'primary',
    title: 'Actualización de la red hidrográfica del Pacífico colombiano con datos 2025-2026.',
    excerpt: 'Se incorporan más de 1,200 nuevos tramos de ríos y quebradas al sistema de información...',
    content: 'El equipo de hidrografía del IIAP completó la actualización de la red hidrográfica del Pacífico colombiano, incorporando más de 1,200 nuevos tramos de ríos y quebradas identificados mediante imágenes satelitales de alta resolución.\n\nLa actualización mejora significativamente la precisión de la cartografía hídrica de la región y permite una mejor planificación de proyectos de acueducto rural, manejo de cuencas y prevención de inundaciones.\n\nLos datos están disponibles para consulta en el Geovisor y descarga desde el Repositorio de Mapas.',
    time: 'Hace 1 semana',
    date: '25 Marzo 2026',
    author: 'Equipo de Hidrografía IIAP',
    category: 'Ambiente',
  },
]
