export const SOLICITUDES_KPIS = [
  { label: 'Total Activas', value: '124' },
  { label: 'En Revisión', value: '32' },
  { label: 'Aprobadas', value: '89%' },
  { label: 'Tiempo Promedio', value: '5.2d' },
]

export const SOLICITUDES_TABLE = [
  {
    id: '#VIG-2024-089',
    tipo: 'Certificado de Uso de Suelo',
    subtipo: 'Predio rural - Quibdó',
    fecha: '12 Oct 2023',
    estado: 'En Proceso',
    estadoColor: 'yellow',
    solicitante: 'Comunidad Negra Río Baudó',
    notas: 'Pendiente de visita técnica programada para el 20 de octubre.',
    timeline: ['Recibida', 'En Revisión', 'En Proceso'],
  },
  {
    id: '#VIG-2024-085',
    tipo: 'Consulta de Linderos',
    subtipo: 'Resguardo Indígena',
    fecha: '10 Oct 2023',
    estado: 'Aprobado',
    estadoColor: 'green',
    solicitante: 'Cabildo Indígena Wounaan',
    notas: 'Linderos validados cartográficamente. Certificado disponible para descarga.',
    timeline: ['Recibida', 'En Revisión', 'En Proceso', 'Aprobado'],
  },
  {
    id: '#VIG-2024-082',
    tipo: 'Estudio Técnico Ambiental',
    subtipo: 'Zona de Protección',
    fecha: '08 Oct 2023',
    estado: 'Rechazado',
    estadoColor: 'red',
    solicitante: 'Empresa Maderas del Pacífico S.A.',
    notas: 'Rechazado por superposición con área protegida. Puede presentar una nueva solicitud con ajustes al polígono.',
    timeline: ['Recibida', 'En Revisión', 'Rechazado'],
  },
  {
    id: '#VIG-2024-079',
    tipo: 'Validación Cartográfica',
    subtipo: 'Cuenca Media Atrato',
    fecha: '05 Oct 2023',
    estado: 'En Proceso',
    estadoColor: 'yellow',
    solicitante: 'Gobernación del Chocó',
    notas: 'En proceso de verificación con datos IGAC. Tiempo estimado: 5 días hábiles.',
    timeline: ['Recibida', 'En Revisión', 'En Proceso'],
  },
  {
    id: '#VIG-2024-074',
    tipo: 'Permiso de Aprovechamiento Forestal',
    subtipo: 'Bosque secundario - Riosucio',
    fecha: '01 Oct 2023',
    estado: 'Aprobado',
    estadoColor: 'green',
    solicitante: 'Asociación Agroforestal Pacífico',
    notas: 'Permiso otorgado por 12 meses con cuota máxima de 80 m³.',
    timeline: ['Recibida', 'En Revisión', 'En Proceso', 'Aprobado'],
  },
  {
    id: '#VIG-2024-071',
    tipo: 'Consulta de Linderos',
    subtipo: 'Área Urbana - Istmina',
    fecha: '28 Sep 2023',
    estado: 'En Proceso',
    estadoColor: 'yellow',
    solicitante: 'Alcaldía Municipal de Istmina',
    notas: 'Solicitud en cruce con base catastral municipal. Requiere georreferenciación adicional.',
    timeline: ['Recibida', 'En Revisión', 'En Proceso'],
  },
  {
    id: '#VIG-2024-068',
    tipo: 'Estudio Técnico Ambiental',
    subtipo: 'Humedal Costero - Bahía Solano',
    fecha: '25 Sep 2023',
    estado: 'Aprobado',
    estadoColor: 'green',
    solicitante: 'Instituto de Investigaciones del Pacífico',
    notas: 'Estudio aprobado. Informe final publicado en el repositorio IIAP.',
    timeline: ['Recibida', 'En Revisión', 'En Proceso', 'Aprobado'],
  },
  {
    id: '#VIG-2024-063',
    tipo: 'Certificado de Uso de Suelo',
    subtipo: 'Zona industrial - Quibdó',
    fecha: '20 Sep 2023',
    estado: 'Rechazado',
    estadoColor: 'red',
    solicitante: 'Constructora Pacífico Verde Ltda.',
    notas: 'Zona declarada de conservación hídrica. No compatible con uso industrial solicitado.',
    timeline: ['Recibida', 'En Revisión', 'Rechazado'],
  },
]

export const TRAMITE_TYPES = [
  { value: '', label: 'Seleccione una opción' },
  { value: 'uso-suelo', label: 'Certificado de Uso de Suelo' },
  { value: 'linderos', label: 'Consulta de Linderos' },
  { value: 'estudio-ambiental', label: 'Estudio Técnico Ambiental' },
  { value: 'validacion', label: 'Validación Cartográfica' },
  { value: 'aprovechamiento', label: 'Permiso de Aprovechamiento Forestal' },
  { value: 'otro', label: 'Otro' },
]
